name: Deploy Frontend to Production

on:
  push:
    branches: [master, deploy]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            # Ensure directory exists with correct permissions
            mkdir -p /var/www/html
            rm -rf /var/www/html/*

      - name: Copy build files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html"
          strip_components: 1
